### ISSUE TITLE
Lovelace not accessible

### ISSUE THREAD

**Issue by razvanmdobre** [SebRut/pygrocy#158] opened 2021-03-08 14:40 UTC
**Describe the bug**
I cannot access the UI of Home Assistant.
In the home-assistant.log I found lots of errors like this:

> 2021-03-08 12:21:42 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.event(event: state_changed).data.new_state(state: binary_sensor.grocy_missing_products).attributes.missing[0].product_barcodes[0]=<pygrocy.grocy_api_client.ProductBarcode object at 0xa7bcac40>(<class 'pygrocy.grocy_api_client.ProductBarcode'>
2021-03-08 12:21:42 WARNING (Recorder) [homeassistant.components.recorder] State is not JSON serializable: <state binary_sensor.grocy_missing_products=on; missing=[{'name': 'My product name', 'id': 5, 'product_group_id': None, 'available_amount': None, 'best_before_date': None, 'barcodes': ['20456887'], 'product_barcodes': [<pygrocy.grocy_api_client.ProductBarcode object at 0xa7bcac40>], 'amount_missing': 1.0, 'is_partly_in_stock': False}], friendly_name=Grocy missing products, icon=GrocyEntityIcon.MISSING_PRODUCTS @ 2021-03-08T12:21:42.740123+02:00>
2021-03-08 12:21:47 ERROR (MainThread) [homeassistant.components.http.view] Unable to serialize to JSON: Object of type ProductBarcode is not JSON serializable

The log file grows to 1GB and maybe more.

**Expected behavior**
Being able to use the lovelace UI as before.

**To Reproduce**
1. Go to the main URL of Home Assistant OR open the Home Assistant mobile app
2. A blank page is displayed forever with the message "loading data" 

**What is your installed versions of Home Assistant, Grocy and this integration?**
Home Assistant core-2021.3.2
Grocy v3.0.1
Grocy integration v3.0.1

**How do you have Grocy installed? Add-on or external?**
add-on 
**Have you added debugging to the log, and what does the log say?**
no
**JSON service data (if related to using a service)**
n/a

**Additional context**
I had to hard reboot my Raspberry Pi and then disable quickly the Grocy integration add-on.
If not doing that quickly after reboot, I have the same issue.

**Comment by renarena** [comment] 2021-03-10 23:21
same here, the only way to get lovelace loaded is to restart hassio while webpage is loading and not reload it before you have disabled grocy integration.

**Comment by isabellaalstrom** [comment] 2021-03-12 08:07
Do you guys have barcodes associated with your products?

**Comment by trunks403** [comment] 2021-03-12 08:27
I have the same problems and yes i do barcodes with my products

**Comment by razvanmdobre** [comment] 2021-03-12 10:53
yes, I have barcodes.

**Comment by SebRut** [comment] 2021-03-21 12:47
Hey! I finally got the time to look into this, but it seems that this cant be fixed in pygrocy. The issue is that python doesn't know how to serialize the `ProductBarcode` object, but AFAIK it isn't possible to make objects serializable in python without changing the call to `json.dumps`. This call is located in homeassistant so the only way to fix this would be to change the data provided to HA in the custom component. I'm not sure how to do this, but other components had similar problems in the past (https://github.com/home-assistant/core/pull/34540/files).

I'm closing this for now, as I think this has to be fixed in the custom component unfortunately (@isabellaalstrom).

**Closed by SebRut** 2021-03-21 12:47 UTC
Labels: bug

**Comment by isabellaalstrom** [comment] 2021-03-21 18:49
Thanks, I will try to fix.

**Comment by ludeeus** [comment] 2021-04-11 10:39
@SebRut The default JSON decoder works with custom objects, if they have `str` as a parent object, I do that here <https://github.com/ludeeus/awesomeversion/blob/main/awesomeversion/awesomeversion.py#L21>

**Comment by SebRut** [comment] 2021-04-12 05:02
@ludeeus thank you for the hint, that sounds like a way to fix this. But I'm not sure if I like this solution because it leads to pygrocy being altered to be specifically compatible with HA by implementing a workaround.

**Comment by ludeeus** [comment] 2021-04-12 08:03
Not really, that would enable the serialization of theses objects without creating and passing in a custom encoder to the dumper.
Everyone that uses this lib and JSON would benefit

**Comment by ludeeus** [comment] 2021-04-12 08:51
Another option that will be easier to implement is to implement a [custom encoder](https://github.com/custom-components/grocy/blob/master/custom_components/grocy/json_encode.py) in this lib, and use that for the `toJson()` in https://github.com/SebRut/pygrocy/blob/develop/pygrocy/base.py#L13
`json.dumps(self.as_dict(), cls: GrocyJSONEncoder)`
